### ISSUE TITLE
×、÷の演算子表記

### ISSUE THREAD

**Issue by c0a21038** [suzukikoushi/ProjExD#10]
https://github.com/suzukikoushi/ProjExD/blob/856a58ebf28b3b998f7115c6e96242987ea1bab6/ex02/calc.py#L16

このままだと上の欄に「×、÷」ではなく「*、/」で表示されてしまうので「×、÷」で表示されるようにした方がいいと思います。

**Comment by suzukikoushi** [comment]
技術不足でした。勉強します。
